# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DFWTProject' do

    pod 'AFNetworking', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
    pod 'YYModel'
    pod 'Masonry'
    pod 'MBProgressHUD+Add'
    pod 'IQKeyboardManager'
    pod 'CYLTabBarController'
    pod 'SDWebImage'
    pod 'LEEAlert'
    pod 'TZImagePickerController'
    pod 'DZNEmptyDataSet'
    pod 'MJRefresh'
    pod 'BEMCheckBox'
    pod 'SDCycleScrollView'
    pod 'RATreeView'
    pod 'FSCalendar'
end
